### ISSUE TITLE
Memory Leak in OpenSSL AES Encryption/Decryption Demo

### ISSUE THREAD

**Issue by mgiannopoulos24** [huiliang-liu/aes_cbc_encryption#1]
**Description:**
There are memory leaks in the AES encryption/decryption demo program caused by dynamically allocated memory that is not freed after use. The specific issues are as follows:

1. The function `hex_2_string` allocates memory for a string representation of hexadecimal data. The caller (printf) does not free this allocated memory, leading to memory leaks.
2. This issue occurs at two locations in the code:
- In the `aes_init` function when printing the key and IV.
- In the `main` function when printing the ciphertext.

**Steps to Reproduce:**

- Compile the code using `gcc main.c -lcrypto -o a.out`.
- Run the program with a key argument `./a.out qwerty`.
- Observe the memory usage increases due to memory not being freed.

**Expected Behavior:**
Memory allocated by hex_2_string should be freed after use to prevent memory leaks.

**Actual Behavior:**
Memory allocated by hex_2_string is not freed, leading to memory leaks.

**Resolution:**
The code has been modified to store the result of `hex_2_string` in a variable, use it, and then free the allocated memory after it is no longer needed. The changes are reflected in the `aes_init` and `main` functions.

The following lines have been added to free the allocated memory:

- `aes_init` after `printf("pwd size %d, val %s, salt %s\n", key_data_len, key_data, salt);`:
```c
unsigned char *key_hex = hex_2_string(key, 32);
unsigned char *iv_hex = hex_2_string(iv, 16);
printf("Key size %d, val %s, iv %s\n", i, key_hex, iv_hex);
free(key_hex);
free(iv_hex);
// The rest remain the same
```

- `main` after `ciphertext = aes_encrypt(en, (unsigned char *)input[i], &len);`
```c
unsigned char *ciphertext_hex = hex_2_string(ciphertext, strlen(ciphertext));
printf("OK: ciphertext: %s\n", ciphertext_hex);
free(ciphertext_hex);
// The rest remain the same
```

By making these changes, the program no longer leaks memory in these sections.

**Comment by huiliang-liu** [comment]
@mgiannopoulos24 Thank you for your contribution!
I have fixed it in the latest commit.
